blank_issues_enabled: true
contact_links: []

issue_templates:
  - name: 🐛 Bug Report
    description: Report something that is broken or not working as expected.
    labels: [bug]
    file: bug_report.md

  - name: ✨ Feature Request
    description: Suggest a new feature or improvement.
    labels: [enhancement]
    file: feature_request.md

  - name: ♿ Accessibility Improvement
    description: Propose a change to make the project more accessible.
    labels: [accessibility, good first issue]
    file: accessibility_improvement.md 